[mypy]
python_version = 3.10
disable_error_code = import-untyped

[mypy-wandb.*,pytorch_tabnet.*,ts.*,dask.*,distributed,lightgbm,mlserver.*,polars,torch,datasets,transformers,huggingface_hub.*,peft.*,unsloth,litserve]
ignore_missing_imports = True
