
import os
import textwrap

from huggingface_hub import list_repo_files, list_repo_commits, \
    hf_hub_download

from flask import Flask, request, render_template_string, \
    render_template, Response


BRANCH_NAME = "retrain-pipelines_pipeline-card"
HF_TOKEN = os.getenv("HF_TOKEN", None)
ERROR_PAGE = "index.html"

app = Flask(__name__, template_folder='/app')

@app.errorhandler(Exception)
def handle_exception(error):
    # status code, default to 500
    status_code = getattr(error, 'code', 500)
    error_msg = str(error) or 'An unknown error occurred.'
    app.logger.error(
        f"{request.remote_addr} - Exception occurred: {error_msg}",
        exc_info=error)

    return render_template(ERROR_PAGE, error_msg=error_msg), \
           status_code


@app.route('/robot.txt')
def robot_txt():
    content = textwrap.dedent("""\
        User-agent: *
        Disallow: /

        # This endpoint serves as an API to render repo-hosted pipeline-card items. 
        # It complements model-versions generated by the retrain-pipelines library 
        # and published on the Hub.
        # This Space serves as an API endpoint to render
        # repo-hosted pipeline-card items.
        # It complements model-versions that the retrain-pipelines library generates
        # and publishes on the Hub.

        # To explore, browse model cards on the Hub and
        # follow "retraining pipeline-card" links.
    """)
    return Response(content, mimetype='text/plain')


@app.route('/', methods=['GET'])
def preview_html():
    model_repo_id = request.args.get('model_repo_id')
    if not model_repo_id:
        error_msg="Please provide a \"model_repo_id\" parameter"
        app.logger.error(f"{request.remote_addr} - {error_msg}",
                         exc_info=False)
        return render_template(
                    ERROR_PAGE, error_msg=error_msg), \
               400
    version_id = request.args.get('version_id')
    if not version_id:
        error_msg="Please provide a \"version_id\" parameter"
        app.logger.error(f"{request.remote_addr} - {error_msg}",
                         exc_info=False)
        return render_template(
                    ERROR_PAGE, error_msg=error_msg), \
               400

    try:
        pipeline_card_filename = get_pipeline_card_filename(
            model_repo_id=model_repo_id,
            banch_name=BRANCH_NAME,
            subfolder=version_id,
            hf_token=HF_TOKEN
        )

        content = open(hf_hub_download(
                repo_id=model_repo_id,
                repo_type="model",
                revision=BRANCH_NAME,
                subfolder=version_id,
                filename=pipeline_card_filename,
                token=HF_TOKEN,
                # cache_dir="/usr/local/.cache"
            )).read()
        return render_template_string(content)
    except Exception as e:
        error_msg = f"Error fetching pipeline-card: {str(e)}"
        app.logger.error(f"{request.remote_addr} - {error_msg}",
                         exc_info=False)
        return render_template(
                    ERROR_PAGE, error_msg=error_msg), \
               500


def get_pipeline_card_filename(
    model_repo_id: str,
    banch_name: str,
    subfolder: str,
    hf_token: str
) -> str:
    """
    There can be more than one pipeline-card
    portable html file per model version
    since run can be 'resumed', for instance
    at the 'pipeline_card' step itself.
    In such cases, we consider the latest.
    """
    
    files = list_repo_files(
        repo_id=model_repo_id,
        repo_type="model",
        revision=banch_name,
        token=hf_token
    )
    
    pipeline_card_files = [f for f in files if f.startswith(f"{subfolder}/")]
    if 0 == len(pipeline_card_files):
        raise Exception(f"No pipeline-card exists for \"{subfolder}\".")
    elif 1 < len(pipeline_card_files):
        commits = list_repo_commits(
            repo_id=model_repo_id,
            revision=banch_name,
            repo_type="model",
            token=hf_token
        )
        latest_commit = None
        latest_commit_time = None
        pipeline_card = None
        for commit in commits:
            files = list_repo_files(
                repo_id=model_repo_id,
                revision=commit.commit_id,
                repo_type="model",
                token=hf_token
            )
            for file in files:
                if file in pipeline_card_files:
                    commit_time = commit.created_at
                    if latest_commit_time is None or commit_time > latest_commit_time:
                        latest_commit_time = commit_time
                        html_pipeline_card_path = file
                        latest_commit = commit
    else:
        html_pipeline_card_path = pipeline_card_files[0]
    
    return os.path.basename(html_pipeline_card_path)


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=7860)


