# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_trace.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10task_trace.proto\x12\ntasktraces\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n\tTaskTrace\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08microsec\x18\x04 \x01(\x05\x12\x14\n\x0cmicrosec_idx\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x0e\n\x06is_err\x18\x07 \x01(\x08\",\n\x08TraceAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2L\n\x10TaskTraceService\x12\x38\n\tSendTrace\x12\x15.tasktraces.TaskTrace\x1a\x14.tasktraces.TraceAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_trace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKTRACE']._serialized_start=66
  _globals['_TASKTRACE']._serialized_end=226
  _globals['_TRACEACK']._serialized_start=228
  _globals['_TRACEACK']._serialized_end=272
  _globals['_TASKTRACESERVICE']._serialized_start=274
  _globals['_TASKTRACESERVICE']._serialized_end=350
# @@protoc_insertion_point(module_scope)
