"""Initial migration

Revision ID: bdff337fbb86
Revises: 
Create Date: 2026-01-05 12:36:08.040070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdff337fbb86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('docstring', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_dump', sa.JSON(), nullable=True),
    sa.Column('ui_css', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskgroups',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('docstring', sa.String(), nullable=True),
    sa.Column('ui_css', sa.JSON(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exec_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('exec_id', 'uuid', name='taskgroup_pk'),
    sa.UniqueConstraint('exec_id', 'order', name='uq_taskgroups_exec_order')
    )
    op.create_table('tasktypes',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('docstring', sa.String(), nullable=True),
    sa.Column('ui_css', sa.JSON(), nullable=True),
    sa.Column('is_parallel', sa.Boolean(), nullable=False),
    sa.Column('merge_func', sa.JSON(), nullable=True),
    sa.Column('taskgroup_uuid', sa.Uuid(), nullable=True),
    sa.Column('children', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['exec_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('exec_id', 'uuid', name='tasktype_pk'),
    sa.UniqueConstraint('exec_id', 'order', name='uq_tasktypes_exec_order')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasktype_uuid', sa.Uuid(), nullable=False),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.JSON(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.CheckConstraint('(end_timestamp IS NULL AND failed IS NULL) OR (end_timestamp IS NOT NULL AND failed IS NOT NULL)', name='end_failed_null_constraint'),
    sa.ForeignKeyConstraint(['exec_id', 'tasktype_uuid'], ['tasktypes.exec_id', 'tasktypes.uuid'], name='task_fk_tasktype'),
    sa.ForeignKeyConstraint(['exec_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasktraces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('microsec', sa.Integer(), nullable=False),
    sa.Column('microsec_idx', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_err', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasktraces')
    op.drop_table('tasks')
    op.drop_table('tasktypes')
    op.drop_table('taskgroups')
    op.drop_table('executions')
    # ### end Alembic commands ###
